name: weather
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15

  #UI
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  bordered_text: ^2.0.0
  flutter_svg: ^1.1.6
  quickalert: ^1.0.1
  intl: ^0.17.0

  #location:
  geolocator: ^9.0.2
  osm_nominatim: ^2.0.1
  google_maps_flutter: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/image/
     - assets/svg/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
